### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by AmirulAndalib** [subinps/MusicPlayer#13]
`[download] Downloading video 24 of 25
[youtube] 50VNCymT-Cs: Downloading webpage
[download] Downloading video 25 of 25
[youtube] EgBJmlPo8Xw: Downloading webpage
[download] Finished downloading playlist: Mix - Witt Lowry - Into Your Arms (Lyrics) ft. Ava Max - [No Rap]
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    from config import Config
  File "/MusicPlayer/config.py", line 39, in <module>
    links.append(f['url'])
KeyError: 'url'`

**Comment by subinps** [comment]
Can you specify the issue a bit more ?
How can i reproduce or how you got this error?

**Comment by AmirulAndalib** [comment]
@subinps thanks for Coming To help But I found out it was An Issue With The YT-DL so After doing some research and experiments i edited the code to YT-DLP....


But Still there is a Bug That Is Radio Player Stops Working After sometimes and only stays Afk...Aster using /restart Command Manually It goes back To Normal...Any Fix for this ?? also I Deployed this Bot On Railway...

**Comment by subinps** [comment]
This iasue was fixed in latest update , you may redeploy with latest source.

**Comment by AmirulAndalib** [comment]
# Sur the bug aint fixed it goes afk aftersometime later i am using this bot on group chat pls fix This time i deployed to heroku.....

**Comment by subinps** [comment]
> # Sur the bug aint fixed it goes afk aftersometime later i am using this bot on group chat pls fix This time i deployed to heroku.....



Are you trying on YouTube videos? Or else radio only?
If youtube video, it may be issue with youtube-dl .

**Comment by AmirulAndalib** [comment]
# radio sur

**Comment by subinps** [comment]
Hmm, let me look into it.

**Comment by AmirulAndalib** [comment]
yes i observed for long time this happens to radio but besides radio my members play music too but after music is ended radio continues and for some hours later it goes afk restarting it fixes the issue but it keeps going afk :/
