### ISSUE TITLE
after doing floodwait fix commit now bot spams more floodwait logs after reboot

### ISSUE THREAD

**Issue by AmirulAndalib** [subinps/MusicPlayer#22]
<code>2021-08-31T13:14:43.370785+00:00 app[worker.1]: Task exception was never retrieved
2021-08-31T13:14:43.370793+00:00 app[worker.1]: future: <Task finished name='Task-520' coro=<GroupCall.__emit_join_payload_callback.<locals>._() done, defined at /usr/local/lib/python3.9/site-packages/pytgcalls/implementation/group_call.py:168> exception=FloodWait('[420 FLOOD_WAIT_X]: A wait of 38 seconds is required (caused by "phone.JoinGroupCall")')>
2021-08-31T13:14:43.370793+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-31T13:14:43.370794+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/implementation/group_call.py", line 175, in _
2021-08-31T13:14:43.370794+00:00 app[worker.1]:     await self.mtproto.join_group_call(
2021-08-31T13:14:43.370795+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 186, in join_group_call
2021-08-31T13:14:43.370795+00:00 app[worker.1]:     response = await self.client.send(
2021-08-31T13:14:43.370796+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/methods/advanced/send.py", line 77, in send
2021-08-31T13:14:43.370796+00:00 app[worker.1]:     r = await self.session.send(
2021-08-31T13:14:43.370797+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 425, in send
2021-08-31T13:14:43.370797+00:00 app[worker.1]:     return await self._send(data, timeout=timeout)
2021-08-31T13:14:43.370798+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/session/session.py", line 395, in _send
2021-08-31T13:14:43.370798+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2021-08-31T13:14:43.370798+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
2021-08-31T13:14:43.370799+00:00 app[worker.1]:     raise getattr(
2021-08-31T13:14:43.370799+00:00 app[worker.1]: pyrogram.errors.exceptions.flood_420.FloodWait: [420 FLOOD_WAIT_X]: A wait of 38 seconds is required (caused by "phone.JoinGroupCall")
2021-08-31T13:14:43.460770+00:00 app[worker.1]: 
2021-08-31T13:14:43.460773+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-31T13:14:43.460774+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
2021-08-31T13:14:43.460774+00:00 app[worker.1]:     await fut
2021-08-31T13:14:43.460774+00:00 app[worker.1]: asyncio.exceptions.CancelledError
2021-08-31T13:14:43.460775+00:00 app[worker.1]: 
2021-08-31T13:14:43.460775+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-08-31T13:14:43.460775+00:00 app[worker.1]: 
2021-08-31T13:14:43.460775+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-31T13:14:43.460776+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
2021-08-31T13:14:43.460776+00:00 app[worker.1]:     fut.result()
2021-08-31T13:14:43.460776+00:00 app[worker.1]: asyncio.exceptions.CancelledError
2021-08-31T13:14:43.460777+00:00 app[worker.1]: 
2021-08-31T13:14:43.460777+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-08-31T13:14:43.460777+00:00 app[worker.1]: 
2021-08-31T13:14:43.460777+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-31T13:14:43.460778+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
2021-08-31T13:14:43.460778+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2021-08-31T13:14:43.460778+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 63, in _process_update
2021-08-31T13:14:43.460779+00:00 app[worker.1]:     await self._update_to_handler[type(update)](update)
2021-08-31T13:14:43.460779+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/mtproto/pyrogram_bridge.py", line 69, in _process_group_call_participants_update
2021-08-31T13:14:43.460779+00:00 app[worker.1]:     await self.group_call_participants_update_callback(wrapped_update)
2021-08-31T13:14:43.460780+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/implementation/group_call.py", line 134, in _group_call_participants_update_callback
2021-08-31T13:14:43.460780+00:00 app[worker.1]:     await self.reconnect()
2021-08-31T13:14:43.460780+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/pytgcalls/implementation/group_call.py", line 319, in reconnect
2021-08-31T13:14:43.460780+00:00 app[worker.1]:     await asyncio.wait_for(self.__emit_join_payload_event.wait(), timeout=self.__ASYNCIO_TIMEOUT)
2021-08-31T13:14:43.460781+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
2021-08-31T13:14:43.460781+00:00 app[worker.1]:     raise exceptions.TimeoutError() from exc
2021-08-31T13:14:43.460781+00:00 app[worker.1]: asyncio.exceptions.TimeoutError</code>

# @subinps i think you should revert this commit its buggy

**Comment by subinps** [comment]
Iam not getting what actually is causing this flood :(

**Comment by AmirulAndalib** [comment]
yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑

**Comment by subinps** [comment]
> yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑

Yeah many reported the same issue. But don't know the fix.
One thing you can try is  generate a new session and log out the user from all session except the new session and try.

**Comment by amanimuhammed** [comment]
> yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑

Actually i think this issue is coming on DC 1 Session. I have used DC 1 in a group then i got the same error (floodwait). Also i am running another VC on DC 5 it is working fine.

**Comment by AmirulAndalib** [comment]
> > yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑
> 
> Actually i think this issue is coming on DC 1 Session. I have used DC 1 in a group then i got the same error (floodwait). Also i am running another VC on DC 5 it is working fine.

# yup mine dc1 too telegram sus

**Comment by AmirulAndalib** [comment]
> > yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑
> 
> Actually i think this issue is coming on DC 1 Session. I have used DC 1 in a group then i got the same error (floodwait). Also i am running another VC on DC 5 it is working fine.

maybe try with dc5 api and hash and dc1 account string

**Comment by RoyalBoy69** [comment]
> > > yes I actually Dont Have Any idea either 😑 In new Patch Aftwr reboot it Keeps Spamming This shitty Timeout For No reason And Even The Music Bot and Player Both Are Admin 😑😑😑 i think its The TG calls issue ....And Also YouTube Playlist Doesnt Work Properly And Some Yotube Videos Dont download and Gets Stucked On Downloading MSG 😑😑😑
> > 
> > 
> > Actually i think this issue is coming on DC 1 Session. I have used DC 1 in a group then i got the same error (floodwait). Also i am running another VC on DC 5 it is working fine.
> 
> maybe try with dc5 api and hash and dc1 account string

im also facing this flood wait

**Comment by Achu2234** [comment]
1. 

- [ ]
